### ISSUE TITLE
Update production without redeploying application servers?

### ISSUE THREAD

**Issue by Bartvds** [django-webpack/django-webpack-loader#105]
Looking through the project it doesn't seem like it support updating the bundles without redeploying all the servers that access this functionality?

Currently we have some home-grown system that pulls version data from cache so we can redeploy separately (it is a read-through on the django caching framework, using the S3 storage as source).

Is this something considered for this project? Or does anyone have an valuable experience that would warn against doing this?

**Comment by owais** [comment]
Currently this is not possible if you use caching but you can do so by disabling caching and just replacing the stats file without re-deploying the rest of the application. Keep in mind that the stats file would be read from disk on every request that calls `render_bundle` template tag.

It should be possible in a future version to use caching and update assets without re-deploying django.

I'm leaving this issue open for now to keep track of the feature request.

**Comment by fjsj** [comment]
For posterity: closing because production management is not part of this library's scope.
