### ISSUE TITLE
webpack_static does not return filename with hash

### ISSUE THREAD

**Issue by Pacu2** [django-webpack/django-webpack-loader#138]
On production, while using:
 `{% webpack_static 'filename.css' %}` 
I think it should resolve to `/some/dir/filename.hash.css`  rather than `/some/dir/filename.css`

It would allow me to get URLs for prefetching/preloading.
Shouldn't `webpack_static` follow `render_bundle` behavior and return hashed version of file?

I cannot use `render_bundle` as  `.css` file tag is created with `type="text/css" rel="stylesheet"` attributes.

**Comment by graingert** [comment]
You can use get_file for css. I've got the same issue but for a `.png`.

These assets don't get placed into `webpack-stats.json`

**Comment by owais** [comment]
This is a known limitation and there have been some discussions on http://github.com/owais/webpack-bundle-tracker to solve this but no one has come up with an implementation yet. Brief description of how I'd like to solve this. https://github.com/owais/webpack-bundle-tracker/pull/17#issuecomment-346741678

PR or other suggestions welcome.

**Comment by huoxy** [comment]
Oh, I am also waiting for this feature.
