### ISSUE TITLE
Read stats.json from DB

### ISSUE THREAD

**Issue by ogonkov** [django-webpack/django-webpack-loader#143]
It's would be really nice to have option to "upload" stats.json to project db, to avoid deploying static file to multiple servers.

We have multiple servers and want to avoid removing server from production for updating stats.json file w/ RPM (our deploy).

**Comment by kutenai** [comment]
I deploy my production builds to a CDN, with a version I'd like to be able to just specify the version, and load the stats file from a known location on the CDN. The stats file can be configured to use a CDN location as the file location, so everything just loads from CDN, based on the 'version'. 

The Version can be specified in the main configuration or the .env files

**Comment by ogonkov** [comment]
@kutenai like that?

```py
WEBPACK_LOADER = {
    'DEFAULT': {
        'STATS_FILE': 'https://foo.aws3.com/bar/assets/webpack-stats.json'
    }
}
```

**Comment by kutenai** [comment]
yes, something like that would work, but when I look at the current code (or, current version I have), it just uses the open method, which I don't think supports a url?

```
    def _load_assets(self):
        try:
            with open(self.config['STATS_FILE'], encoding="utf-8") as f:
                return json.load(f)
```

The code is in webpack_loader.loader.py

**Comment by ogonkov** [comment]
Yes, that's why I open this issue.

Also, having hashes in file on disk looks wrong for me.

**Comment by owais** [comment]
Currently we don't support opening stats files from network and probably never will but I'm open to making the loader class more extensible so we can write simple plugins to load from anywhere. Would be great if someone comes up with the design of how it would work here.
