### ISSUE TITLE
Upgrade Twine?

### ISSUE THREAD

**Issue by brainwane** [django-webpack/django-webpack-loader#153]
I'm one of the maintainers of [Twine](http://twine.readthedocs.io/); your `requirements.txt` file specifies an old version. The new version of Twine is 1.10.0. If there's anything we can do to make your upgrade path easier, please mention it here or [file an issue](https://github.com/pypa/twine/issues/new)?

Also, your `Makefile` mentions the `twine register` command. There's [now no need to "register" a project before initial upload on pypi.org and test.pypi.org](https://packaging.python.org/guides/migrating-to-pypi-org/#registering-package-names-metadata), although it might be necessary on other Python package indexes -- just a heads-up.

**Comment by owais** [comment]
Thanks. It works right now so I don't want to break it but thanks for dropping by and sharing the info. It'll be helpful when I have the time to upgrade.
