### ISSUE TITLE
using with webpack-rtl-plugin

### ISSUE THREAD

**Issue by osamana** [django-webpack/django-webpack-loader#163]
Using `webpack-rtl-plugin` in my webpack configurations produces two main CSS file `main.xxx.css` and `main.xxx.rtl.css`. 
and when I load the stylesheets with `{% render_bundle 'main' 'css' %}`, it loads both files.
how would I go about loading only either one of those files with the `render_bundle` tag?

**Comment by fjsj** [comment]
For posterity: a custom loader is probably necessary. You should re-implement `get_bundle`: https://github.com/django-webpack/django-webpack-loader#extra-webpack_loader-settings-in-django
