### ISSUE TITLE
how to have multiple entries and outputs and easily use them in template

### ISSUE THREAD

**Issue by sant527** [django-webpack/django-webpack-loader#177]
I am having the following Django project structure.

    PROJECTROOT
    ├── package.json
    ├── package-lock.json
    ├── Pipfile
    ├── Pipfile.lock
    │
    ├── DJANGOROOT
    │   ├── db.sqlite3
    │   ├── DJANGOROOT
    │   │   ├── __init__.py
    │   │   ├── settings.py
    │   │   ├── urls.py
    │   │   └── wsgi.py
    │   ├── manage.py
    │    
    │   ├── APP_XYZ   <-- app
    │   │   ├── admin.py
    │   │   ├── apps.py
    │   │   ├── __init__.py
    │   │   ├── migrations
    │   │   │   ├── __init__.py
    │   │   ├── models.py
    │   │   ├── static  <-- app static files
    │   │   │   └── APP_XYZ
    │   │   │       ├── bundles
    │   │   │       │   ├── ANYNAME1-90dfdbd133f2c98a5365.js
    │   │   │       │   └── ANYNAME2-90dfdbd133f2c98a5365.js
    │   │   │       └── js
    │   │   │           ├── ANYNAME1.js
    │   │   │           └── ANYNAME2.js
    │   │   ├── templates  <-- app template files
    │   │   │   └── APP_XYZ
    │   │   │       ├── ANYNAME1.html
    │   │   │       └── ANYNAME2.html
    │   │   ├── tests.py
    │   │   ├── urls.py
    │   │   └── views.py
    │   └── webpack-stats.json
    └── webpack.config.js

```

APP_XYZ can be any app in the django. 

I have created the following folder structure to work with webpack and reactjs:

```
PROJECTROOT/DJANGOROOT/APP_XYZ/static/APP_XYZ/js/  -- to have the source js for reactjs code
PROJECTROOT/DJANGOROOT/APP_XYZ/static/APP_XYZ/bundles/  -- to have the bundled js
```

If i have the source js like
PROJECTROOT/DJANGOROOT/APP_XYZ/static/APP_XYZ/js/ANYNAME.js
then i want a bundle js like
PROJECTROOT/DJANGOROOT/APP_XYZ/static/APP_XYZ/bundles/ANYNAME-hash.js

Here APP_XYZ and ANYNAME will be variables.

For that what should be my webpack config entry and output

**Comment by jpic** [comment]
Show your webpack.config.json, let's see what you got so far ;)

**Comment by sant527** [comment]
Okay i am putting what i tried here:

```
├── package.json
├── package-lock.json
├── Pipfile
├── Pipfile.lock
├── src
│   ├── db.sqlite3
│   ├── krishnacook   <-- Django project
│   │   ├── __init__.py
│   │   ├── settings.py
│   │   ├── urls.py
│   │   └── wsgi.py
│   ├── manage.py
│   ├── polls  <-- django app for testing
│   │   ├── admin.py
│   │   ├── apps.py
│   │   ├── __init__.py
│   │   ├── migrations
│   │   │   ├── __init__.py
│   │   ├── models.py
│   │   ├── static  <-- polls app static files
│   │   │   └── polls
│   │   │       ├── bundles
│   │   │       │   ├── index-90dfdbd133f2c98a5365.js
│   │   │       │   └── questions-90dfdbd133f2c98a5365.js
│   │   │       └── js
│   │   │           ├── index.js
│   │   │           └── questions.js
│   │   ├── templates <-- polls app template files
│   │   │   └── polls
│   │   │       ├── index.html
│   │   │       └── questions.html
│   │   ├── tests.py
│   │   ├── urls.py
│   │   └── views.py
│   └── webpack-stats.json
└── webpack.config.js

```

My webpack.config.js

```
var path = require("path");
var webpack = require('webpack');
var BundleTracker = require('webpack-bundle-tracker');

module.exports = {
  context: __dirname,

  //entry: './src/polls/static/js/index',

  entry: {
    'src/polls/static/polls/bundles/index':  './src/polls/static/polls/js/index',
    'src/polls/static/polls/bundles/questions':  './src/polls/static/polls/js/questions',
   },

  output: {
    path: __dirname,
    filename: "[name]-[hash].js",
  },

  // output: {
  //     path: path.resolve('./src/polls/static/bundles/'),
  //     filename: "[name]-[hash].js",
  // },

  plugins: [
    new BundleTracker({filename: './src/webpack-stats.json'}),
  ],
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader"
        }
      }
    ]
  },
  resolve: {
    extensions: ['*', '.js', '.jsx']
  }

};
```

My settings.py

STATIC_URL = '/static/'

```
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': '',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        # '/home/web_dev/krishnacook_pipenv/webpack-stats.json'
    }
}
```

polls/urls.py

```
from django.urls import path

from .views import PollQuestions, index


urlpatterns = [
    path('', index, name='index'),
    path('questions/', PollQuestions.as_view(), name='questions')
]
```

polls/views,py

```
from django.shortcuts import render

# Create your views here.
from django.views import View

from .models import Question


def index(request):
    return render(request, 'polls/index.html')


class PollQuestions(View):
    title = "Questions"
    template = 'polls/questions.html'

    def get(self, request):
        questions = list(Question.objects.values('pk', 'question_text'))

        context = {
            'question_text': self.title,
            'props': questions,
        }

        return render(request, self.template, context)

```

webpack-stats.json

```
{
  "status": "done",
  "chunks": {
    "src/polls/static/polls/bundles/index": [
      {
        "name": "src/polls/static/polls/bundles/index-90dfdbd133f2c98a5365.js",
        "path": "/home/web_dev/krishnacook_pipenv/src/polls/static/polls/bundles/index-90dfdbd133f2c98a5365.js"
      }
    ],
    "src/polls/static/polls/bundles/questions": [
      {
        "name": "src/polls/static/polls/bundles/questions-90dfdbd133f2c98a5365.js",
        "path": "/home/web_dev/krishnacook_pipenv/src/polls/static/polls/bundles/questions-90dfdbd133f2c98a5365.js"
      }
    ]
  }
}
```

templates/polls/questions

```
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="UTF-8">
 <title>Questions</title>
 </head>
<body>
 <h1>Questions</h1>
 <div id="react"></div>
<script>
  window.props = {{ props|safe }};
  window.react_mount = document.getElementById('react');
</script>
  {% render_bundle 'src/polls/static/polls/bundles/questions' %}

 </body>
</html>
```

templates/polls/index.html

```
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="UTF-8">
 <title>Example</title>
 </head>
 <body>
 <div id="react"></div>
 {% render_bundle 'src/polls/static/polls/bundles/index' %}
 </body>
</html>
```


So when i try:

http://127.0.0.1:8000/polls/

it says:
`http://127.0.0.1:8000/static/src/polls/static/polls/bundles/index-90dfdbd133f2c98a5365.js  404 not found`

So when i try:
http://127.0.0.1:8000/polls/questions

it says:

`http://127.0.0.1:8000/static/src/polls/static/polls/bundles/questions-90dfdbd133f2c98a5365.js 404 not found`

**Comment by sant527** [comment]
no.

**Comment by jpic** [comment]
Instead of :

 {% render_bundle 'src/polls/static/polls/bundles/index' %}

Did you try

 {% render_bundle 'index' %}

**Comment by sant527** [comment]
I solved it by changing the webpack config as:

```
  entry: {
    'polls/bundles/index':  './src/polls/static/polls/js/index',
    'polls/bundles/questions':  './src/polls/static/polls/js/questions',
   },

  output: {
    path: path.join(__dirname, '/src/polls/static/'),
    filename: "[name]-[hash].js",
  },

```

and then stats file become:

```
{
  "status": "done",
  "chunks": {
    "polls/bundles/index": [
      {
        "name": "polls/bundles/index-3e16db0ce7efc4c36f10.js",
        "path": "/home/web_dev/krishnacook_pipenv/src/polls/static/polls/bundles/index-3e16db0ce7efc4c36f10.js"
      }
    ],
    "polls/bundles/questions": [
      {
        "name": "polls/bundles/questions-3e16db0ce7efc4c36f10.js",
        "path": "/home/web_dev/krishnacook_pipenv/src/polls/static/polls/bundles/questions-3e16db0ce7efc4c36f10.js"
      }
    ]
  }
}
```

Now index.html

```
{% load render_bundle from webpack_loader %}
<!DOCTYPE html>
<html>
 <head>
 <meta charset="UTF-8">
 <title>Example</title>
 </head>
 <body>
 <div id="react"></div>
 {% render_bundle 'polls/bundles/index' %}
 </body>
</html>
```

then it points to `http://127.0.0.1:8000/static/polls/bundles/index-3e16db0ce7efc4c36f10.js`

**Comment by jpic** [comment]
You got it :clap:

**Comment by ajiejot** [comment]
> I solved it by changing the webpack config as:
> 
> ```
>   entry: {
>     'polls/bundles/index':  './src/polls/static/polls/js/index',
>     'polls/bundles/questions':  './src/polls/static/polls/js/questions',
>    },
> 
>   output: {
>     path: path.join(__dirname, '/src/polls/static/'),
>     filename: "[name]-[hash].js",
>   },
> ```
> and then stats file become:
> 
> ```
> {
>   "status": "done",
>   "chunks": {
>     "polls/bundles/index": [
>       {
>         "name": "polls/bundles/index-3e16db0ce7efc4c36f10.js",
>         "path": "/home/web_dev/krishnacook_pipenv/src/polls/static/polls/bundles/index-3e16db0ce7efc4c36f10.js"
>       }
>     ],
>     "polls/bundles/questions": [
>       {
>         "name": "polls/bundles/questions-3e16db0ce7efc4c36f10.js",
>         "path": "/home/web_dev/krishnacook_pipenv/src/polls/static/polls/bundles/questions-3e16db0ce7efc4c36f10.js"
>       }
>     ]
>   }
> }
> ```
> Now index.html
> 
> ```
> {% load render_bundle from webpack_loader %}
> <!DOCTYPE html>
> <html>
>  <head>
>  <meta charset="UTF-8">
>  <title>Example</title>
>  </head>
>  <body>
>  <div id="react"></div>
>  {% render_bundle 'polls/bundles/index' %}
>  </body>
> </html>
> ```
> then it points to `http://127.0.0.1:8000/static/polls/bundles/index-3e16db0ce7efc4c36f10.js`

can I see your repository? I still cant see something when it rendered
