### ISSUE TITLE
How to resolve static files from templates? 

### ISSUE THREAD

**Issue by mihalt** [django-webpack/django-webpack-loader#196]
Hi! Thanks for loader. But I haven't understood yet how to resolve static files from django templates. For example 
```<img src="{% static "img/tmp/ava.png" %}" width="50" height="50" alt="Avatar">```

After using of webpack this image can have the name on output like `123456.png`. So I thinked, that if I use `webpack_static` tag it will work, but it didn't want. May be I do something wrong?

**Comment by fjsj** [comment]
This is an old issue, but I'll reply here for reference to others, as we're the new maintainers of the project:

webpack_static is basically static that looks first for publicPath and goes to STATIC_URL as a fallback.

Note that this will get the "original" asset, without having passed through any webpack optimization. If we wanted to get an asset that passed through webpack (with a random string as the name), it's not currently possible (this was discussed in [PR 90 as well](https://github.com/django-webpack/django-webpack-loader/pull/90#issuecomment-299316143)). We'd have to update both packages to allow some form of mapping on the stats file (i.e.: inform in the stats file that foo.png produced 649243593-i.png), although this could be tricky for assets that get splitted into multiple files.

We'll track this in another issue. Closing this one.
