### ISSUE TITLE
django isn't reading my path to images 

### ISSUE THREAD

**Issue by Alaa-mansour** [django-webpack/django-webpack-loader#198]
my project is react django and am using webpack to bundle the files so my problem is that django is reading my js files but not reading my images 

settings.py 
`STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), 'static-cdn')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
`

webpack.common.js
`const path = require("path");
var BundleTracker = require("webpack-bundle-tracker");
const webpack = require("webpack");

module.exports = {
  entry: {
    app: "./src/index.js",
    vendors: ["react"]
  },
  output: {
    filename: "[name].bundle.js",
    path: path.resolve(__dirname, "./static/bundles"),
    publicPath: "/static/bundles/"
  },
  resolve: {
    extensions: [".js", ".jsx"]
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        loader: "babel-loader",
        exclude: /node_modules/,
        query: {
          presets: ["@babel/react"]
        }
      },

      {
        test: /\.css$/,
        use: ["style-loader", "css-loader", "resolve-url-loader"]
      },
      {
        test: /\.scss$/,
        use: [
          "style-loader", // creates style nodes from JS strings
          "css-loader", // translates CSS into CommonJS
          "sass-loader", // compiles Sass to CSS, using Node Sass by default
          "resolve-url-loader"
        ]
      },
      {
        test: /\.(png|svg|jpg|gif|jpe?g)$/,
        use: [
          {
            options: {
              name: "[name].[ext]",
              outputPath: "img/"
            },
            loader: "file-loader"
          }
        ]
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[name].[ext]",
              outputPath: "fonts/"
            }
          }
        ]
      }
    ]
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new BundleTracker({ filename: "./webpack-stats.json" }),
    new webpack.NoEmitOnErrorsPlugin()
  ]
};
`

here is the error :
http://127.0.0.1:8000/img/pen.jpg 404 (Not Found)
 i have been stuck with this error for 4 days

**Comment by lenheard** [comment]
Did you manage to get the solution... Because I'm also stuck on this for many day...
I also can't find a solution on the net...
**Please help**

**Comment by lenheard** [comment]
Looks like I might have cracked it...
This is my webpack.config..:
    output: {
        path: path.join(__dirname, 'assets/dist'),
        publicPath: '/static/',
        filename: '[name]-[hash].js'
    },

and then in django settings...:

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "assets/dist"),
                    )
STATIC_URL = "/static/"

In my component...:

import fav from "./favicon.png";
........

    render() {
        return (
                      <div>
                            <img src={fav}/>
                            <h1>Hello....!!</h1>
                        </div>
        );
    }
}

I hope it helps

**Comment by harem234** [comment]
> 
> 
> Looks like I might have cracked it...
> This is my webpack.config..:
> output: {
> path: path.join(__dirname, 'assets/dist'),
> publicPath: '/static/',
> filename: '[name]-[hash].js'
> },
> 
> and then in django settings...:
> 
> STATICFILES_DIRS = (
> os.path.join(BASE_DIR, "assets/dist"),
> )
> STATIC_URL = "/static/"
> 
> In my component...:
> 
> import fav from "./favicon.png";
> ........
> 
> ```
> render() {
>     return (
>                   <div>
>                         <img src={fav}/>
>                         <h1>Hello....!!</h1>
>                     </div>
>     );
> }
> ```
> 
> }
> 
> I hope it helps

it work like a charm.
