### ISSUE TITLE
I enable webpack hot replacement, but how can I enable it for django project?

### ISSUE THREAD

**Issue by ghost** [django-webpack/django-webpack-loader#201]
In other word, I havn't to press F5 to preview the modification, just like a pure frontend project with hot replacement enabled?

**Comment by khadegd** [comment]
You will need to update your static urls to point at webpack server-generated assets. Use this for reference -> https://github.com/khadegd/django-webpack-starter

**Comment by fjsj** [comment]
@joaopslins please check if there's something we can do on README to clarify this.

**Comment by joaopslins** [comment]
@fjsj I believe https://github.com/django-webpack/django-webpack-loader/tree/master/examples/hot-reload already handles this case.
