### ISSUE TITLE
Package Needs Updates 

### ISSUE THREAD

**Issue by shonin** [django-webpack/django-webpack-loader#212]
The django community is very dependent on this package, however, it's now outdated enough that it no longer works according to the documentation. Can the maintainer please add some other admins onto this project so we can get it working again?

If not, I'm happy to fork it and start accepting pull requests for fixes.

**Comment by shonin** [comment]
Here is the setup I'm using that is functional (django 3 and webpack 4):

`Django==3.0.1`

```
"devDependencies": {
    "autoprefixer": "^9.7.3",
    "css-loader": "^3.4.0",
    "node-sass": "^4.13.0",
    "postcss-loader": "^3.0.0",
    "sass-loader": "^8.0.0",
    "style-loader": "^1.1.2",
    "webpack": "^4.41.4",
    "webpack-bundle-tracker": "^0.4.3",
    "webpack-cli": "^3.3.10"
  }
```


**File structure**
```
| - project/
| - - settings.py
| - static/
| - - dist/
| - - - main-<hash>.js
| - - src/
| - - - js/
| - - - - index.js
| - - - scss/
| - - - - index.scss
| - webpack.config.js
```

**`settings.py`**
```python
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

INSTALLED_APPS = [
    # ...
    'django.contrib.staticfiles',
    'webpack_loader',
    # ...
]

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

WEBPACK_LOADER = {
    'DEFAULT': {
        'CACHE': not DEBUG,
        'BUNDLE_DIR_NAME': 'dist/',
        'STATS_FILE': os.path.join(BASE_DIR, 'webpack-stats.json'),
        'POLL_INTERVAL': 0.1,
        'TIMEOUT': None,
        'IGNORE': [r'.+\.hot-update.js', r'.+\.map']
    }
}
```

**`webpack.config.js`**
```javascript
const path = require('path');
const BundleTracker = require('webpack-bundle-tracker');


module.exports = {
    mode: 'development',
    entry: './static/src/js/index.js',
    output: {
        path: path.resolve(__dirname, 'static/dist'),
        filename: "[name]-[hash].js",
    },
    module: {
        rules: [
            {
                test: /\.(scss)$/,
                use: [{
                    loader: 'style-loader', // inject CSS to page
                }, {
                    loader: 'css-loader', // translates CSS into CommonJS modules
                }, {
                    loader: 'postcss-loader', // Run postcss actions
                    options: {
                        plugins: function () { // postcss plugins, can be exported to postcss.config.js
                            return [
                                require('autoprefixer')
                            ];
                        }
                    }
                }, {
                    loader: 'sass-loader' // compiles Sass to CSS
                }]
            },
        ]
    },
    plugins: [
        new BundleTracker({filename: './webpack-stats.json'}),
    ]
};
```

**base html template**
```jinja2
{% load render_bundle from webpack_loader %}
<body>
<!-- app html -->
{% render_bundle 'main' %}
</body>
```

**Comment by owais** [comment]
I'd say this works as intended for the webpack version it supports (<=2). Support for newer ones was never explicitly added but is being worked on over at https://github.com/owais/webpack-bundle-tracker. `webpack-bundle-tracker@1.0.0-alpha.0` was just released that ships support for webpack4 among other things.  We are tracking what should go in 1.0.0 for webpack-bundle-tracker here: https://github.com/owais/webpack-bundle-tracker/milestone/1

**Comment by owais** [comment]
Created an initial ticket to track what will go into 1.0.0 here: https://github.com/owais/django-webpack-loader/issues/215

**Comment by keikoro** [comment]
@shonin I have a question about your file structure:

> **File structure**
> 
> ```
> | - project/
> | - - settings.py
> | - static/
> | - - dist/
> | - - - main-<hash>.js
> | - - src/
> | - - - js/
> | - - - - index.js
> | - - - scss/
> | - - - - index.scss
> | - webpack.config.js
> ```

Seeing as the `static` dir is on the same level as `project`... Is `project` the directory containing all your Django project's files (just not visualised here), and `static` is the _output_ folder for all static content?

Relatedly, @owais, when you say the following at the start of the config instructions in the README:
> Assuming `BASE_DIR` in settings refers to the root of your django app.

you actually mean Django project (/site) rather than app, right? Not trying to nitpick, but in a Django context, usage of the word "app" can get confusing. It's a small thing, but I wouldn't mind sending a PR to improve the wording here.

**Comment by keikoro** [comment]
@owais Only seeing the thumbs up now, I think GH doesn't notify about reactions. ^^
