### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by owais** [django-webpack/django-webpack-loader#215]
Starting this issue to track what should go into 1.0.0. This will be a backwards incompatible release so we have a chance to improve things we couldn't before.  For one, 1.0.0 will only support webpack 4 and newer. 

Please add a comment or link to an issue if you'd like it to be resolved in 1.0.0

**Comment by oleggromov** [comment]
I suppose this one shall go in a new major version: https://github.com/owais/django-webpack-loader/issues/227

**Comment by jonathan-s** [comment]
#182 seems like a very much wanted feature as well.

**Comment by owais** [comment]
> #182 seems like a very much wanted feature as well.

Bundle tracker  1.0.0-alpha.0 has support for this. 1.0 of this package will add support for 1.0.0 bundle tracker. That should cover webpack 4. PRs welcome.

**Comment by owais** [comment]
> I suppose this one shall go in a new major version: #227

Yes, if someone sends a PR, we can release 1.0-alpha.x

**Comment by gilmrjc** [comment]
I've sent the PR https://github.com/owais/django-webpack-loader/pull/232 to address that.
