### ISSUE TITLE
Upgrade to webpack-bundle-tracker to 1.0.0 

### ISSUE THREAD

**Issue by owais** [django-webpack/django-webpack-loader#218]
1.0.0-alpha.0 has been released and it only supports webpack 4 and newer. django-webpack-loader 1.0.0 should drop support for older webpack versions and rely on 1.0.0-alpha.0 of webpack-bundle-tracker. This mainly means updating the test suite and making sure it passes with webpack4 and bundle tracker 1.0.0

**Comment by owais** [comment]
WIP effort here: #217. Let me know if anyone would like to take it over.

**Comment by gilmrjc** [comment]
I've sent a PR https://github.com/owais/django-webpack-loader/pull/232 implementing the new version of webpack-bundle-tracker. It uses version alpha.1 and it handles the new stats format.

**Comment by rvlb** [comment]
We've merged #232. Release will follow soon.
