### ISSUE TITLE
Error reading webpack-stats.json. Are you sure webpack has generated the file and the path is correct?

### ISSUE THREAD

**Issue by joseph-vedadi** [django-webpack/django-webpack-loader#224]
![image](https://user-images.githubusercontent.com/17168374/74973001-8dc82680-53d7-11ea-83ac-22dba6b5bd6c.png)
How am I supposed to fix this issue? 
This issue comes ones very often (not every single time). or so.
How can I install the latest and greatest version?

**Comment by brightgems** [comment]
have same issue, what's the solution?

**Comment by VFS** [comment]
Hello, @joseph-vedadi ! I had the same problem, and it was a typo on my `WEBPACK_LOADER['DEFAULT']['STATS_FILE']` setting.

```
# settings.py
...
WEBPACK_LOADER = {
    'DEFAULT': {
        'BUNDLE_DIR_NAME': 'dist/',
        'STATS_FILE': BASE_DIR / 'frontend' / 'webpack-stats.json'
    }
}
```

Maybe you should check if the path is written correctly, or post your directory structure and `WEBPACK_LOADER` settings so I can try to help you track the error.

**Comment by okekec** [comment]
@VFS I am having a similar error when installing doccano. I ran the following code below on my git bash.

```
$ git clone https://github.com/chakki-works/doccano.git
$ cd doccano
$ pip install -r requirements.txt
$ cd app
$ python manage.py createsuperuser 
Username: admin
Email address: admin@example.com
Password: **********
Password (again): *********
Superuser created successfully.
$ python manage.py runserver
```

Here is what I get after running the following code to set up a local clone of doccano on my desktop. I go to http://127.0.0.1:8080/login/. Then I get the error below.
![Doccano server error](https://user-images.githubusercontent.com/50752054/97086442-e72cc900-15e8-11eb-95cc-3d642a9df6f2.JPG)
![Doccano server error 1](https://user-images.githubusercontent.com/50752054/97086452-f3b12180-15e8-11eb-960c-e6d4420630e2.JPG)

My Environment
Operating System: Windows 10 Pro version 1903
Python Version Used: 3.6.10
When you install doccano: 2 days ago
How did you install doccano (Heroku button etc): git clone + docker-compose

**Comment by engin-can** [comment]
> We need version 0.4.3 of webpack-bundle-tracker because the files Django is expecting will not be automatically generated > in the same way if we use the latest alpha version. Please note, 0.4.3 is the latest stable release as of April 2020. If we don't > specify this version, npm will pull down the latest alpha version which will not work the same.
