### ISSUE TITLE
Blog Post link is dead 

### ISSUE THREAD

**Issue by MLI-DS** [django-webpack/django-webpack-loader#229]
Hi, 
Just wanted to point out that the link to the blog post ( https://owais.lone.pw/blog/webpack-plus-reactjs-and-django/) is dead. 

Even if its a little old It seems like it contains lots of useful set up info , I'd love to get access to it ! 

Thanks for all your work on this project

**Comment by jonathan-s** [comment]
You can reach using the wayback machine for the time being: http://web.archive.org/web/20181027093509/https://owais.lone.pw/blog/webpack-plus-reactjs-and-django/

**Comment by MLI-DS** [comment]
Thanks! 
Should have though of it straight away.

**Comment by owais** [comment]
It's back up. There was a temporary issue with the domain.
