### ISSUE TITLE
How to migrate from 0.6 to 1.0 ?

### ISSUE THREAD

**Issue by pulse-mind** [django-webpack/django-webpack-loader#272]
## Question
Hello

Thank you for you job. 
Do you have a guide line to migrate from 0.6 to 1.0 please? 

## What have you tried so far?
I tried but I got 
```
    bundle = get_loader(config).get_bundle(bundle_name)
File "...\lib\site-packages\webpack_loader\loader.py", line 90, in get_bundle
    asset = assets['assets'][chunk]
KeyError: 'assets'
```

**Comment by rvlb** [comment]
Hi @pulse-mind, we'll be adding this to the docs when [this PR](https://github.com/django-webpack/django-webpack-loader/pull/271) gets merged later today.

Regarding the issue, `django-webpack-loader==1.0.0` requires the stats file formatting from `webpack-bundle-tracker@1.0.0-alpha.1`. We'll be also releasing `webpack-bundle-tracker@1.0.0` today to ensure versions parity.

**Comment by pulse-mind** [comment]
Thanks a lot !!
