### ISSUE TITLE
KeyError 'assets' when upgrading from 0.7.0 to 1.0.0

### ISSUE THREAD

**Issue by clearyusc** [django-webpack/django-webpack-loader#278]
Hi there,

When I upgraded from 0.7.0 to 1.0.0 I noticed this error.
```File "...python/lib/python3.8/site-packages/webpack_loader/loader.py", line 90, in get_bundle
asset = assets['assets'][chunk]
 KeyError: 'assets'```

**Comment by fjsj** [comment]
Hi @clearyusc , please make sure you're using webpack-bundle-tracker@1.0.0 on your `package.json`. Check: https://github.com/django-webpack/django-webpack-loader#migrating-from-version--100

**Comment by fjsj** [comment]
Closing for now, I'll reopen if the issue persists for you.
