### ISSUE TITLE
KeyError: 'assets' in Django Template on get_bundle 'main'

### ISSUE THREAD

**Issue by faulander** [django-webpack/django-webpack-loader#281]
settings.py:
```
# Webpack Loader Configuration
WEBPACK_LOADER = {
    "DEFAULT": {
        "CACHE": not DEBUG,
        "BUNDLE_DIR_NAME": "webpack_bundles/",
        "STATS_FILE": os.path.join(UI_DIR, "webpack-stats.json"),
        "POLL_INTERVAL": 0.1,
        "TIMEOUT": None,
        "IGNORE": [r".+\.hot-update.js", r".+\.map"],
        "LOADER_CLASS": "webpack_loader.loader.WebpackLoader",
    }
}
```
vue.config.js:
```
const BundleTracker = require("webpack-bundle-tracker");

module.exports = {
    publicPath: "http://0.0.0.0:8080/",
    outputDir: './dist/',
    runtimeCompiler: true,

    pages: {
        main: {
            entry: 'src/main.js',
        },

    },

    chainWebpack: config => {
        config.optimization
            .splitChunks(false)

        config
            .plugin('BundleTracker')
            .use(BundleTracker, [{ filename: './webpack-stats.json' }])

        config.resolve.alias
            .set('__STATIC__', 'static')

        config.devServer
            .public('http://0.0.0.0:8080')
            .host('0.0.0.0')
            .port(8080)
            .hotOnly(true)
            .watchOptions({ poll: 1000 })
            .https(false)
            .headers({ "Access-Control-Allow-Origin": ["\*"] })
    }
};
```
In webpack.stats.json:
`{"status":"done","publicPath":"http://0.0.0.0:8080/","chunks":{"main":[{"name":"js/main.js","publicPath":"http://0.0.0.0:8080/js/main.js","path":"/Users/xxx/Projects/xxx/ui/dist/js/main.js"}]}}`

In index.html:
```
{% load render_bundle from webpack_loader %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    {% include "head_part.html" %}

</head>
...
...
...
    {% render_bundle 'main' %}

</body>

</html>
```

**Comment by lfsando** [comment]
![image](https://user-images.githubusercontent.com/10608706/121067437-6ef2cc80-c7a1-11eb-91ee-9732a75f544f.png)

`assets` variable is a dict with a key `chunks` not `assets` again as the code is trying to run.

**Comment by fjsj** [comment]
Please provide the `webpack-bundle-tracker` version you're using

**Comment by pabiadzinski** [comment]
I encountered the same problem. I downgraded django-webpack-loader version from 1.0.0 to 0.7.0. It works.

django-webpack-loader==0.7.0
django==3.2.4
webpack-bundle-tracker": "^0.4.3"

**Comment by fjsj** [comment]
Since 1.0.0, the versions of django-webpack-loader and webpack-bundle-tracker are synced.
So if you're using 1.0.0 in one, please use in another.

webpack-bundle-tracker 0.4.3 is an old release. Could someone please inform if this issue is happening in 1.0.0 (or in current version, 1.1.0)?

**Comment by ibrahimawadhamid** [comment]
I updated both `webpack-bundle-tracker` and `django-webpack-loader` to the latest version `1.1.0` and that fixed the issue.

**Comment by fjsj** [comment]
Thanks @ibrahimawadhamid 
Closing this for now.
If anyone faces the same issue, please comment here.
