### ISSUE TITLE
Fix RemovedInDjango41Warning about default_app_config

### ISSUE THREAD

**Issue by flaiming** [django-webpack/django-webpack-loader#291]
`default_app_config` should be removed from https://github.com/django-webpack/django-webpack-loader/search?q=default_app_config to fix Django 4.1 deprecation warning.

`RemovedInDjango41Warning: 'webpack_loader' defines default_app_config = 'webpack_loader.apps.WebpackLoaderConfig'. Django now detects this configuration automatically. You can remove default_app_config.`

**Comment by fjsj** [comment]
Closed by #290
