### ISSUE TITLE
Don't try to check files that should be ignored in get_bundle

### ISSUE THREAD

**Issue by patrickdamery** [django-webpack/django-webpack-loader#294]
I kept getting an error when trying to load Vue via django-webpack-loader. For some reason my `webpack-stats.json` file included in the chunks a `.map.css` file that didn't even exist. This causes a key error when trying to load the asset for this chunk.

Considering I was ignoring all `.map` files as specified in the documentation this error shouldn't even come up as we should be ignoring this file in the first place.

**Comment by patrickdamery** [comment]
I see that this was actually addressed in #280 and a fix was made in #286. When will the updates be released?

**Comment by fjsj** [comment]
Hi @patrickdamery , we'll release the fix soon, possibly tomorrow or next Monday. Thanks for the issue.

**Comment by fjsj** [comment]
@joaopslins please close this once the release is made

**Comment by joaopslins** [comment]
Fixed in 1.3.0
