### ISSUE TITLE
STATIC_URL = '/static_dev/' is not respected

### ISSUE THREAD

**Issue by sowinski** [django-webpack/django-webpack-loader#326]
Hi,

in my development machine I have set 
`STATIC_URL = '/static_dev/' `

But django-webpack is not respecting this change, why?

In my template the generate dir is pointing to .../static/... instead to .../static_dev/.... 
I use django-webpackloader Version 0.7

Any idea?

**Comment by fjsj** [comment]
@sowinski sorry you're having issues, but please use the latest version and check the README. Check if your webpack.config.js uses a `publicPath` that's equal to your `STATIC_URL`. We don't support 0.7 anymore, so I'm closing this for now.
