### ISSUE TITLE
should FakeWebpackLoader also mock get_assets?

### ISSUE THREAD

**Issue by tlambert03** [django-webpack/django-webpack-loader#346]
I found myself needing to create an extended FakeWebpackLoader when using `webpack_static`:

```python
class MockWebpackLoader(FakeWebpackLoader):
    def get_assets(self):
        return {}
```

(otherwise you hit an `IOError` when it attempts to read).  Would that be a good PR?  or should I be doing this differently anyway?

**Comment by fjsj** [comment]
Please feel free to open the PR, thanks!
