### ISSUE TITLE
Support publicPath: "auto"

### ISSUE THREAD

**Issue by caseyjhol** [django-webpack/django-webpack-loader#350]
Currently, setting `publicPath: "auto"` results in a stats file with:

```json
{
  "status": "done",
  "assets": {
    "lib/css/layers.416d91365b44e4b4f477.png": {
      "name": "lib/css/layers.416d91365b44e4b4f477.png",
      "path": "/Users/casey/build/public/lib/css/layers.416d91365b44e4b4f477.png",
      "publicPath": "autolib/css/layers.416d91365b44e4b4f477.png"
    },
    ...
}
```
"auto" is just prepended to publicPath. Which of course won't work out of the box. Considering "auto" is the default value in Webpack, it might be nice to support setting `publicPath: "auto"` and add a PUBLIC_PATH option to the loader config that would handle concatenation for us. We're using a custom LOADER_CLASS in the meantime.

**Comment by fjsj** [comment]
@caseyjhol, I agree this would be the best. Can you share your custom LOADER_CLASS?

**Comment by fjsj** [comment]
@caseyjhol I've made some changes add support for `publicPath: "auto"`. I tested it in production with a S3 config, but it would be good if you also test it.

Install the fixes (not released yet):
```
npm install "git+https://github.com/django-webpack/webpack-bundle-tracker.git#b970a34957298c72e6c42874a43c8339a70fde61"
pip install "git+https://github.com/django-webpack/django-webpack-loader.git#cc013e4d87f28921131d80098929671c7e014d75"
```

Use a output like:
```javascript
const path = require("path");

module.exports = {
  // ...
  output: {
    path: path.resolve("./frontend/webpack_bundles/"),
    publicPath: "auto",
    filename: "[name]-[chunkhash].js",
  },
};
```

and let me know if it works for your use case.
