### ISSUE TITLE
Webpack loader render_bundle adds extra hash to file name on production

### ISSUE THREAD

**Issue by kevinmachstudio** [django-webpack/django-webpack-loader#93]
Using webpack version 1.13.2 to load my Javascript file in index.html file of my Django application. My webpack configuration creates the correct file so I don't think it's a Webpack issue. When I check the source code of my index.html it's looking for a different file name, so I'm thinking it's a webloader loader issue. For example, webpack creates main.js successfully in the right folder and I can see it when I go to that url, but then for some reason the webpack loader looks for main.3kea0sh39.js, which doesn't exist. It seems like a bug in render_bundle but I'm not sure. Here's my base and production configurations:

index.html

`{% render_bundle 'main' 'js' %}
`

becomes

`<script type="text/javascript" src="/static/dist/main.3kea0sh39.js" ></script>
`

base:
```

var path = require("path")
var webpack = require("webpack")
var BundleTracker = require('webpack-bundle-tracker')

var APP_DIR = path.resolve(__dirname, 'project/src/app');
var config = {
	entry: path.resolve(__dirname, 'project/src/app') + '/index.jsx',
	output: {
		path: path.resolve('project/src/bundles/'),
		filename: "[name].js"
	},
	plugins: [
	],
	module: {
		loaders: [
			{
				test: /\.css$/,
				loaders: ["style", "css", "sass"]
			}
		]
	},
	resolve: {
		modulesDirectories: ['node_modules'],
		extensions: ['', '.js', '.jsx', '.css', '.scss']
	}
}
module.exports = config;
```

prod:
```

var webpack = require('webpack')
var BundleTracker = require('webpack-bundle-tracker')

var config = require('./webpack.base.config.js')

config.output.path = require('path').resolve('project/static/dist')

config.devtool = 'source-map'


config.plugins = config.plugins.concat([

	new BundleTracker({filename: 'project/webpack-stats-prod.json'}),
	new webpack.optimize.UglifyJsPlugin({
		minimize: true,
		compress: { 
			warnings: false 
		}
	}),
])

config.module.loaders.push(
	{ test: /\.jsx?$/, exclude: /node_modules/, loader: 'babel' }
)


module.exports = config
```

**Comment by owais** [comment]
Hi @kevinmachstudio. This looks strange. Would it be possible for you to share a minimal example to reproduce the problem as a git repo so I can easily reproduce and fix it?

**Comment by Psykar** [comment]
This is probably due to static file configuration actually, assuming you're using ManifestStaticFilesStorage (or something similar)
https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#manifeststaticfilesstorage
